package edu.uniajc.model;
// Generated Nov 23, 2017 9:56:21 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleFactura generated by hbm2java
 */
@Entity
@Table(name = "detalle_factura")
public class DetalleFactura implements java.io.Serializable {

	private int codigo;
	private Factura factura;
	private Producto producto;
	private Integer cantidad;
	private Double precioTotal;

	
	@Override
	public String toString() {
		return "DetalleFactura [codigo=" + codigo + ", factura=" + factura.getCodigo() + ", producto=" + producto.getDescripcion() + ", cantidad="
				+ cantidad + ", precioTotal=" + precioTotal + "]";
	}

	public DetalleFactura() {
	}

	public DetalleFactura(int codigo) {
		this.codigo = codigo;
	}

	public DetalleFactura(int codigo, Factura factura, Producto producto, Integer cantidad, Double precioTotal) {
		this.codigo = codigo;
		this.factura = factura;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioTotal = precioTotal;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_factura")
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_producto")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio_total", precision = 17, scale = 17)
	public Double getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(Double precioTotal) {
		this.precioTotal = precioTotal;
	}

}
