package edu.uniajc.model;
// Generated Nov 23, 2017 9:56:21 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tercero generated by hbm2java
 */
@Entity
@Table(name = "tercero")
public class Tercero implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String apellido;
	private String cargo;
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public Tercero() {
	}

	public Tercero(int codigo) {
		this.codigo = codigo;
	}

	public Tercero(int codigo, String nombre, String apellido, String cargo, Set<Factura> facturas) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.apellido = apellido;
		this.cargo = cargo;
		this.facturas = facturas;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "cargo", length = 50)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tercero")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
